---@meta
---@class TItem
---@class TGameBuff
---@class TGameAnimation
---@class TGameMapEventPage
---@class TGameItem
---@class TGameCharacter
---@class TGameJob
---@class TGameMapStub
---몬스터 정보가 들어있는 객체입니다
---@class TGameMonster
---@class TGameSkill
---@class TGameStrings
---@class TGameTileset
---공용 이벤트 정보
---@class TGameCommonEvent
---@field conditionSwitch1ID number
---@field l_name string
---@field name string
---@field page TGameMapEventPage
---@field startCondition number
---@field targetPlayerSelector System.Collections.Generic.List
-- TGameCommonEvent = {}
